### ISSUE TITLE
How to get faces with different angles before training?

### ISSUE THREAD

**Issue by geyongtao** [Jack-CV/PCN#10]
![opencv_rotate](https://user-images.githubusercontent.com/22744013/39619392-40d6abd0-4fba-11e8-902f-0bae3956a3bf.gif)
Hi,@Jack-CV. As is shown in the picture, when rotating a face, the bounding box will be rotated accordingly. Thus would lead some undefined pixes around a face（e.g. black pixes in the above image). How do you handle this problem? In other words, how do you ajust bounding box label according to the rotate angle?

**Comment by Jack-CV** [comment]
I convert rectangle label to square label [link](https://github.com/Jack-CV/PCN/issues/8). And the following pictures show how I adjust bounding box label.
![image](https://user-images.githubusercontent.com/38135837/39736719-f4dca1ec-52b3-11e8-8219-d3425ad3a4d9.png)
![image](https://user-images.githubusercontent.com/38135837/39736735-0ce6d79e-52b4-11e8-806f-5d8983b7c1d2.png)
![image](https://user-images.githubusercontent.com/38135837/39736750-21fa8964-52b4-11e8-8ea7-5fecfd87fce9.png)
![image](https://user-images.githubusercontent.com/38135837/39736760-2e5bcba0-52b4-11e8-8be0-76f5b7464648.png)
![image](https://user-images.githubusercontent.com/38135837/39736780-4d30484e-52b4-11e8-9b2e-9077248c9804.png)

**Comment by geyongtao** [comment]
I got it. Thanks a lot!

**Comment by geyongtao** [comment]
@Jack-CV 还有一个问题，请问第一个阶段训练的face/non face分类输出和bounding box回归对第二阶段的网络训练有帮助吗？（同理：第二阶段的分类输出和bounding box回归对第三阶段的网络）

- 按照我的理解，论文中提出的第二个网络不是对第一个网络的bounding box回归进行精调，而是从头开始训练。单个网络的face/non face classification和bounding box regression只作为其训练时自身的监督信号，在测试阶段，只利用到第一和第二阶段网络的calibration classification输出。

**Comment by Jack-CV** [comment]
@geyongtao  在我的实现中，各个阶段的边框回归没有关联，各自训练各自的。各阶段的face/non face分类有关联，体现在下一级的负样本是上一级过滤得到。我记得Cascade CNN和MTCNN应该也是这样训练的。

**Comment by Edwardmark** [comment]
@Jack-CV 您好，请问你训练的时候，是先把人脸截出来吗？还有就是PCN训练的框是正立的还是斜着的，看您上面的例子似乎框是正立的？那这个正立的框是怎么得到的呢？是取斜着框的x和y的最大最小得到的吗？

**Comment by Edwardmark** [comment]
@Jack-CV 另一个问题，你旋转的时候没有考虑图片被边缘截掉的问题吗？是不是应该扩大边界？

**Comment by Rogerluojie** [comment]
@Jack-CV 你好，想请问训练第三阶段的角度回归时，怎样计算角度的回归值标签数据
