### ISSUE TITLE
get face candidate by sliding window and image pyramid？

### ISSUE THREAD

**Issue by KangolHsu** [Jack-CV/PCN#11]
You said you use sliding window and image pyramid to get face candidates?
 why do you use fully convolution like MT-CNN?
thanks

**Comment by Jack-CV** [comment]
@KangolHsu  The fully convolution network in stage one equals sliding window logically. Specifically, the stride in fully convolution network equals the sliding window stride. This is a widely used trick in recent methods, such as [OverFeat](https://arxiv.org/abs/1312.6229), [DDFD](https://arxiv.org/abs/1502.02766), [MTCNN](https://arxiv.org/abs/1604.02878v1), etc. So I don’t specify this in paper.

**Comment by Jack-CV** [comment]
@KangolHsu Figure 6 is used to illustrate the network parameters. We transform the fully connected layers in stage one into convolutional layers during test phase. This made it possible to efficiently run the CNN on images of any size. As mentioned above, this is a widely used trick, so I don't  specify the transformation in Figure 6.

**Comment by KangolHsu** [comment]
OK 
![1zvf2la a o v uo s7pz7r](https://user-images.githubusercontent.com/7868842/39863608-bc55f464-5479-11e8-896e-86d42f97bde7.png)
