### ISSUE TITLE
请问PCN.dat model文件的存储类型和格式是怎样的?

### ISSUE THREAD

**Issue by Roger8** [Jack-CV/PCN#12]
请问PCN.dat model文件的存储类型和格式是怎样的? @Jack-CV

**Comment by Jack-CV** [comment]
@Roger8 你好，实际上，dat文件就是caffemodel文件。但现在这个有点其他问题直接读不了。我最近会更新一下。

**Comment by Jack-CV** [comment]
@Roger8  模型已经更新，可以按照caffemodel格式读取了
