### ISSUE TITLE
how to run the demo on gpu?

### ISSUE THREAD

**Issue by Edwardmark** [Jack-CV/PCN#13]
hi, jack-cv, I see that in compile.sh there is a CPU_ONLY tag, how to run it on GPU?

**Comment by Edwardmark** [comment]
@jack-cv

**Comment by Edwardmark** [comment]
@Jack-CV Now, I can run your demo on CPU, but I want to run your demo on GPU, what is your cuda and cudnn version?

**Comment by Edwardmark** [comment]
Looking forward to your reply.@Jack-CV

**Comment by Edwardmark** [comment]
upvote daily, please comment @Jack-CV

**Comment by Jack-CV** [comment]
@Edwardmark 你好，最近事情太多，抱歉回复不及时。现在这个程序里我直接写成了用CPU运行。我过一阵子会更新一版程序，到时候会增加GPU设置的接口。

**Comment by Edwardmark** [comment]
@Jack-CV 多谢您的回复，真的感谢

**Comment by Edwardmark** [comment]
@Jack-CV 请问您设置了GPU运行的接口了吗？

**Comment by tuoyuxiang** [comment]
同求GPU运行...估计可以达到实时！
