### ISSUE TITLE
Coordinate Calculation problems

### ISSUE THREAD

**Issue by Edwardmark** [Jack-CV/PCN#14]
@Jack-CV what do face.x, face.y, face.width mean in PCN.h? I cannot understand your coordinates calculation, could you please give me a hint?
Best, 
Edward

**Comment by Jack-CV** [comment]
@Edwardmark  x，y是左上角坐标，w是框的边长

**Comment by Edwardmark** [comment]
@Jack-CV 我本来也是这样理解的，但是在你的画图代码里，你首先将x1,y1,x2,y2都经过了Rotate_points函数才画出来的，所以这就是我不太明白的地方。如果x1,y1是左上角坐标，那当框是斜着的时候，为啥x2 = face.width + face.x - 1;
y2 = face.width + face.y - 1;
上面两个式子貌似在框是水平的时候是成立的，但是框是斜着的时候貌似不对吧，理解不到位，求讲解，谢谢您了。

**Comment by Jack-CV** [comment]
@x，y, w表示没有被旋转的框的左上角坐标和边长，旋转之后的坐标可以根据x, y, w和旋转角度计算得到

**Comment by Edwardmark** [comment]
@Jack-CV谢谢了，真的感谢您的耐心解答。
