### ISSUE TITLE
is there a docker image or another version? 

### ISSUE THREAD

**Issue by hian90** [Jack-CV/PCN#15]
I tried this development environment more than 10 times and it did not work.
 If you do not mind, I wonder if you can tell me the way to get a docker image or another version (tensor flow, keras, etc).

Thank you again for your hard work, it is greatly appreciated.

**Comment by Jack-CV** [comment]
@hian90  Hi hian，can you show me your problems？

**Comment by hian90** [comment]
there are two way that i'm trying..



------------------------------------first Way ( Ubuntu 16.04 , opencv2.4.11, caffe using OpenBLAS)------------------------------------

1. get docker image which installed opencv 2.4.11
      docker run -it spekulant <https://hub.docker.com/u/spekulant/>/ubuntu-opencv <https://hub.docker.com/r/spekulant/ubuntu-opencv/>
2. install caffe (using OpenBLAS, cuda version: 9.1) 
     http://iamyoonkim.tistory.com/6 <http://iamyoonkim.tistory.com/6> (it was written in korean.. )
3. set the CAFFEROOT as you told, command like below
    sh compile.sh video

then, Errors show like this
   root@80df16cba6cf:~/PCN/code# sh compile.sh video
rm video
rm: cannot remove 'video': No such file or directory
compile video
/usr/bin/ld: warning: libboost_system.so.1.54.0, needed by libPCN.so, not found (try using -rpath or -rpath-link)
/tmp/cc9K9pbL.o: In function `main':
video.cpp:(.text.startup+0xad): undefined reference to `PCN::PCN(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libPCN.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
libPCN.so: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
libPCN.so: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
done




------------------------------------first Way ( Ubuntu 14.04 , opencv2.4.8, caffe NOT using OpenBLAS but atlas?)------------------------------------


1. get docker image which installed opencv 2.4.8, caffe

2. set the CAFFEROOT and command like below
    sh compile.sh video


then, Errors show like this
root@905fbe16fc0e:~/PCN/code# sh compile.sh video
rm video
rm: cannot remove 'video': No such file or directory
compile video
/usr/bin/ld: warning: libcaffe.so.1.0.0, needed by libPCN.so, not found (try using -rpath or -rpath-link)
libPCN.so: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
collect2: error: ld returned 1 exit status
done





Thank you for your prompt reply ;)

**Comment by Edwardmark** [comment]
@hian90 you need to compile caffe in ubuntu 14.04+cuda8.0+caffe1.0.0, and you need to compile caffe mannually. I met the same question as you, and I solve it by:  
`docker pull nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04`
and compile caffe without cmake but mannualy make following the official guide

**Comment by Edwardmark** [comment]
@Jack-CV I build a caffe docker image that can be used in your project, this is my github repo, would you please add it to your readme.md so that others can easily reimplement your demo?
[https://github.com/Edwardmark/caffe-docker](url)

**Comment by Jack-CV** [comment]
@Edwardmark Thanks for your work, it's cool. I will update this project in a few days, by the time I will add that link to my readme.
