### ISSUE TITLE
When use different min_face_size, got different result on same picture? A confusing question.

### ISSUE THREAD

**Issue by Edwardmark** [Jack-CV/PCN#16]
Hi, Jack
I have a question，when change detector.SetMinFaceSize(48) to detector.SetMinFaceSize(20), the result changes. When test with 30, there is no face detected. test with the same input，the output is different with rotate of the angle, I am confused and want to know your opinion, the test input is as follows：  
![img2](https://ws1.sinaimg.cn/large/006aJkuugy1frivqybe24j306q06qacn.jpg)  
when the minFaceSize is 21 or 48, the output is as follows：  
![img48](https://ws1.sinaimg.cn/large/006aJkuuly1frivsjaqrmj306q06q41b.jpg)
when the minFaceSize is 20, the output is as follow：  
![img20](https://ws1.sinaimg.cn/large/006aJkuuly1frivta454kj306q06qgof.jpg)    
when the minFaceSize is 30, the output is as follow：  
![img30](https://ws1.sinaimg.cn/large/006aJkuugy1friwbr82icj306q06qdio.jpg)    
It turns out that the output angle has been flipped up and down or just lost the face, could you please give me a hint what causes that? Should I change the ImagePyramidScaleFactor?      
Best,  
Edward

**Comment by Edwardmark** [comment]
It is so strange, did I miss something? Please help me out.@Jack-CV

**Comment by Edwardmark** [comment]
And another question, what is the difference between your fast version and the original version?Do you compile your code with GPU support? Why is it fast?

**Comment by Jack-CV** [comment]
@Edwardmark 
It's normal. When we change min face size, the image pyramid changes as well. So the result might be different. Indeed, there exists some cases this detector can not handle.

The networks in fast version is smaller than original.

**Comment by Edwardmark** [comment]
@Jack-CV Thanks, Jack. so the fast version still can not run on GPU?

**Comment by Edwardmark** [comment]
@Jack-CV Please comment, thanks.

**Comment by BrownOfSummer** [comment]
Did you figured out why the result changes as the MinFaceSize changes; And how to set MinFaceSize in your experience? @Edwardmark
