### ISSUE TITLE
compile error on ubuntu16.04

### ISSUE THREAD

**Issue by HandsomeHans** [Jack-CV/PCN#18]
OS: Ubuntu 16.04
Protobuf version: 2.6.1
OpenCV version: 2.4.13
gcc & g++ version: 5.4.0

When I compoling picture.cpp, I got a error as below
`compile picture
/tmp/ccewgFHU.o: In function `main':
picture.cpp:(.text.startup+0x77): undefined reference to `PCN::PCN(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libPCN.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
libPCN.so: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
libPCN.so: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
done
`

I searched some information by google, soameone said this was because the version of gcc&g++ was too high. Then I changed gcc&g++ version to 4.8. However, another error occured.
`compile picture
/tmp/ccdYSnpl.o: In function `main':
picture.cpp:(.text.startup+0x140): undefined reference to `cv::imread(std::string const&, int)'
picture.cpp:(.text.startup+0x6b1): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
libPCN.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
libPCN.so: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
libPCN.so: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
collect2: error: ld returned 1 exit status
done
`

Really have no sense to deal with this. Could you please help me?

**Comment by caicaifuyi** [comment]
I have the same problem.
compile picture
/usr/bin/ld: warning: libboost_system.so.1.54.0, needed by libPCN.so, not found (try using -rpath or -rpath-link)
/tmp/ccbyCAvR.o: In function `main':
picture.cpp:(.text.startup+0x140): undefined reference to `cv::imread(std::string const&, int)'
picture.cpp:(.text.startup+0x6b1): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
libPCN.so: undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::string)'
libPCN.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
libPCN.so: undefined reference to `caffe::Net<float>::Net(std::string const&, caffe::Phase, int, std::vector<std::string, std::allocator<std::string> > const*)'
collect2: error: ld returned 1 exit status
done

**Comment by Edwardmark** [comment]
I met this before, you should use ubuntu 14.04, or use my docker file:  
https://github.com/Edwardmark/caffe-docker

**Comment by HandsomeHans** [comment]
@Edwardmark Maybe use ubuntu 14.04 is the only way to deal with all the problems. How do you do visualization work in docker?

**Comment by Edwardmark** [comment]
@HandsomeHans  Just save the image instead.

**Comment by HandsomeHans** [comment]
@Edwardmark Lol, thanks a lot. I wanna run it on a webcam. I am thinking to install vnc server in docker, and visualize a desktop on local host.

**Comment by Jack-CV** [comment]
@HandsomeHans  @caicaifuyi   I have released the source code

**Comment by yeluohuazhifou** [comment]
Have you solved the problem?

**Comment by yeluohuazhifou** [comment]
I met the same problem as you.
