### ISSUE TITLE
GPU version？？

### ISSUE THREAD

**Issue by jiagh2010** [Jack-CV/PCN#19]

**Comment by Edwardmark** [comment]
Would you please kindly release the GPU version code? I want to compare PCN with other face detection algorithm in speed. I compare it with S3FD with minFaceSize = 16, but PCN's CPU version is  50% slower than S3fd's GPU version, so I want to do a fair comparison. @Jack-CV

**Comment by Edwardmark** [comment]
Finally, I found one way to run it on GPU.

**Comment by jiagh2010** [comment]
@Jack-CV @Edwardmark How to run it on GPU？

**Comment by Edwardmark** [comment]
@jiagh2010 Just set Caffe_mode GPU

**Comment by Minotaur-CN** [comment]
The speed is not boost on GPU_mode. Anyone has the same problem?
