### ISSUE TITLE
 您好，请问你训练的时候，是先把人脸截出来吗？还有就是PCN训练的框是正立的还是斜着的？

### ISSUE THREAD

**Issue by Edwardmark** [Jack-CV/PCN#21]
看[rotate](https://github.com/Jack-CV/PCN/issues/10)这里面写到，似乎框是正立的？
那这个正立的框是怎么得到的呢？是取斜着框的x和y的最大最小得到的吗？
另一个问题：你在训练时如何控制各个角度人脸的比例呢？每个角度都生成相同比例的人脸吗？

**Comment by Andrawzyf** [comment]
@Edwardmark 他这个在caffe怎么训练的，有网络模型么？

**Comment by Edwardmark** [comment]
@Andrawzyf 没有给模型，所以我想自己训一个

**Comment by Andrawzyf** [comment]
@Edwardmark 我也想自己训练个

**Comment by Edwardmark** [comment]
@Andrawzyf  我生成了360度全角度的数据，目前在训练phase1，但是发现二分类的准确率不高，请问你训练的结果怎么样？我对每张图片生成了20张旋转图片，角度随机分布。

**Comment by JsBlueCat** [comment]
@Edwardmark  这个 min L = L cls + λ reg · L reg + λ cal · L cal ,   第一个台阶的  reg 和 cal 取值你设了多少？

**Comment by JsBlueCat** [comment]
@Edwardmark  作者说随机旋转的图片然后训练的，他也没给图片分布。服从高斯分布的图片来20张 然后旋转吗？
