### ISSUE TITLE
人脸特征点没有返回标定？？人脸对齐？？

### ISSUE THREAD

**Issue by jiagh2010** [Jack-CV/PCN#24]

**Comment by Edwardmark** [comment]
没有特征点训练任务

**Comment by Edwardmark** [comment]
楼主你训练了吗？我训第一步角度分类准确率只有90%左右，跟论文的95%有一定差距啊

**Comment by jiagh2010** [comment]
你好，
      我在调用libPCN.so程序时，发现输入多张不同尺寸图像，会导致内存使用不断增加，最后导致死机，您可以看看这是怎么回事吗？？更新一下so文件！谢谢！
      代码啊如下：


 #include "PCN.h"
#include <iostream>
// caffe
#include <caffe/caffe.hpp>
#include <caffe/layers/memory_data_layer.hpp>
#include <boost/python.hpp>


using namespace std;
using namespace caffe;
using namespace boost::python;




void fromPython()
{
    Caffe::set_mode(Caffe::CPU);


    PCN detector("PCN.caffemodel");
    detector.SetMinFaceSize(40);
    detector.SetScoreThresh(0.97);
    detector.SetImagePyramidScaleFactor(1.414);
    detector.SetVideoSmooth(false);




    for (int i = 1; i <= 636; i++)
    {
std::cout << endl;
std::cout << "序号:" << i << endl;
        cv::Mat img = cv::imread("/home/jiagh/deepl/facedata/data/" + std::to_string(i) + ".jpg");
        if(!img.data) continue;
       
        std::vector<Window> faces = detector.DetectFace(img);


        std::cout<<"facedetect:"<<faces.size()<<endl;
    }
}














在2018年6月25日 13:45，Edwardmark<notifications@github.com> 写道：

楼主你训练了吗？我训第一步角度分类准确率只有90%左右，跟论文的95%有一定差距啊

**Comment by Edwardmark** [comment]
@jiagh2010 内存泄漏了吗？

**Comment by jiagh2010** [comment]
你好，
     程序运行没有报错，但是不断吃内存，最后kill


在2018年6月29日 16:31，Edwardmark<notifications@github.com> 写道：

@jiagh2010 内存泄漏了吗？

**Comment by Edwardmark** [comment]
@jiagh2010 我用不同图片测试过没有问题啊，你可以把完整代码放上来吗？

**Comment by jiagh2010** [comment]
如下，就是简单的调用，只不过输入测试的数据多些


#include "PCN.h"
#include <iostream>
// caffe
#include <caffe/caffe.hpp>
#include <caffe/layers/memory_data_layer.hpp>
#include <boost/python.hpp>


using namespace std;
using namespace caffe;
using namespace boost::python;




void fromPython()
{
    Caffe::set_mode(Caffe::CPU);


    PCN detector("PCN.caffemodel");
    detector.SetMinFaceSize(40);
    detector.SetScoreThresh(0.97);
    detector.SetImagePyramidScaleFactor(1.414);
    detector.SetVideoSmooth(false);




    for (int i = 1; i <= 636; i++)
    {
std::cout << endl;
std::cout << "序号:" << i << endl;
        cv::Mat img = cv::imread("/home/jiagh/deepl/facedata/data/" + std::to_string(i) + ".jpg");
        if(!img.data) continue;
       
        std::vector<Window> faces = detector.DetectFace(img);


        std::cout<<"facedetect:"<<faces.size()<<endl;
    }
}


int main()
{


    fromPython();
    return 0;
}


在2018年6月29日 16:36，Edwardmark<notifications@github.com> 写道：

@jiagh2010 我用不同图片测试过没有问题啊，你可以把完整代码放上来吗？

**Comment by jiagh2010** [comment]
你好，
     "PCN程序运行没有报错，但是不断吃内存，最后kill"的问题找到没有？？
     谢谢！

**Comment by Edwardmark** [comment]
@jiagh2010 没看出程序的问题，我用多张图片跑过，没有出现类似问题，建议你再检查下其他部分，或者跟作者联系一下。

**Comment by jiagh2010** [comment]
视频中是我录制的读取部分本地636幅图像观察内存使用率的结果，可以看到内存使用率由2.3增加到9.0。


在2018年7月2日 14:16，Edwardmark<notifications@github.com> 写道：

@jiagh2010 没看出程序的问题，我用多张图片跑过，没有出现类似问题，建议你再检查下其他部分，或者跟作者联系一下。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易邮箱大师发来的云附件
pcn测试.mp4(79.5MB,2018年7月17日 15:5 到期)
下载

**Comment by Edwardmark** [comment]
@jiagh2010 建议你按照作者picture.cpp或者video.cpp的形式改写，因为不知道作者.so文件是如何生成的，所以最好在示例基础上修改，你前面include的头文件完全没有用啊，我完全按picture.cpp跑2万张图片都没有内存泄漏问题的。

**Comment by Edwardmark** [comment]
@jiagh2010  下面的include完全没有用啊，你按照作者的示例跑一下试一试
#include <caffe/caffe.hpp>
#include <caffe/layers/memory_data_layer.hpp>
#include <boost/python.hpp>


using namespace std;
using namespace caffe;
using namespace boost::python;

**Comment by Edwardmark** [comment]
@jiagh2010 作者代码没有问题，我测试过，建议你按照作者示例使用即可。

**Comment by jiagh2010** [comment]
好的，我试试


在2018年7月2日 15:28，Edwardmark<notifications@github.com> 写道：

@jiagh2010 我是在docker中跑的，我怀疑是你环境的问题，这些细节问题作者也没办法解决啊，要不你试试我的docker？
https://github.com/Edwardmark/caffe-docker

**Comment by jiagh2010** [comment]
你是用GPU跑的？？？我用的虚拟机下的ubuntu14.04，CPU跑的？




在2018年7月2日 15:29，jiagh2010<jiagh2010@163.com> 写道：


好的，我试试


在2018年7月2日 15:28，Edwardmark<notifications@github.com> 写道：

@jiagh2010 我是在docker中跑的，我怀疑是你环境的问题，这些细节问题作者也没办法解决啊，要不你试试我的docker？
https://github.com/Edwardmark/caffe-docker

**Comment by Edwardmark** [comment]
@jiagh2010 CPU跑的

**Comment by Edwardmark** [comment]
@jiagh2010 为啥要用虚拟机？装个ubuntu多好

**Comment by jiagh2010** [comment]
没这条件，而且还是在笔记本上装的虚拟机




在2018年7月2日 15:37，Edwardmark<notifications@github.com> 写道：

@jiagh2010 为啥要用虚拟机？装个ubuntu多好

**Comment by Edwardmark** [comment]
在笔记本上装个双系统试试啊

**Comment by jiagh2010** [comment]
在服务器上跑cpu的吃内存，跑gpu的吃显存，占存储都是一点一点增大，数据量还不够，你的那个docker有离线的吗，我再试试




在2018年7月2日 16:17，Edwardmark<notifications@github.com> 写道：

在笔记本上装个双系统试试啊

**Comment by Edwardmark** [comment]
@jiagh2010 你是不是每次识别的时候都初始化了一次模型？ main.cpp第九行是什么？
 by 0x5A45C77: PCN::PCN(std::string) (in /home/jiagh/deepl/人脸相关/PCN/PCN/code/PCN/libPCN.so)

**Comment by jiagh2010** [comment]
模型只初始化一次（ps：如果初始化多次会出错，so文件内部函数没做成可多次调用的形式），第9行就是加载PCNmodel，然后进入封装的函数


#include "PCN.h"   
#include <string>  
#include <iostream>


using namespace std;


int main()
{
    PCN detector("PCN.caffemodel");
    detector.SetMinFaceSize(40);
    detector.SetScoreThresh(0.97);
    detector.SetImagePyramidScaleFactor(1.414);
    detector.SetVideoSmooth(false);


    for (int i = 0; i < 3; i++)
    { 
        cv::Mat img = cv::imread("/home/jiagh/deepl/facedata/data2/"+std::to_string(i+1)+".jpg");
        if(!img.data) continue;
        std::vector<Window> faces = detector.DetectFace(img); 
        cout<<faces.size()<<endl;
        std::vector<Window>().swap(faces);
    }
   


    return 0;
}




在2018年7月5日 15:43，Edwardmark<notifications@github.com> 写道：

@jiagh2010 你是不是每次识别的时候都初始化了一次模型？ main.cpp第九行是什么？
by 0x5A45C77: PCN::PCN(std::string) (in /home/jiagh/deepl/人脸相关/PCN/PCN/code/PCN/libPCN.so)

**Comment by howg0924** [comment]
@jiagh2010 您好，我也遇到和您类似的内存洩漏的问题，请问您后来有没有解决此问题呢？请问是修改了哪裡？非常感谢。

**Comment by jnxyatmjx** [comment]
me too, don't know where memory leak
