### ISSUE TITLE
Use the network in paper, cannot train orientation task well?

### ISSUE THREAD

**Issue by Edwardmark** [Jack-CV/PCN#26]
question1:  I use the network in the paper, to train the PCN-2, but the accuracy is only about 80% in the training datset, cannot get 96% , any ideas?    

question2: I parse your caffemodel, and see the input is three data, i.e. data1, data2, data3, could you tell me what the three data mean and how to generate them?    

Best,
Edward

**Comment by JsBlueCat** [comment]
@Edwardmark  how do you train the angle? the bounding-box seems to be up-right

**Comment by Edwardmark** [comment]
@JsBlueCat  根据角度和旋转矩阵计算出坐标即可。

**Comment by Rogerluojie** [comment]
@Edwardmark 你好，可以分享一下你的训练网络的文件吗？

**Comment by Jack-CV** [comment]
@Edwardmark @JsBlueCat @Rogerluojie  I have released the source code
