### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by geyongtao** [Jack-CV/PCN#3]
Hi, @Jack-CV. It is really a nice work to detect the large pose face.  Can you explain how to get the rotate angular label of  face to supervise the trainning. As I know, WIDER FACE don't have the facial landmark. Do you use one of the facial landmark detect algorithms to get the facial landmark and then calculate the facial angular or just label all the faces manually?

Besides, what do you mean that "we rotate the initial training images uniformly in the range of..." in section 2.3 and 2.4 of the paper?  As a beginner, I am confused of the statement.

**Comment by Jack-CV** [comment]
Thanks for your interest in our work.  WIDER FACE don't have the facial landmark or rotate angular label. We use the images only containing upright faces as our training images. and rotate them to the rotation-in-plane(RIP) angle we want, the rotation angle is the rotate angular label. 

The range of  input faces' RIP angle in the first stage is [-180, 180], so we need to rotate the training images in the range of  [-180, 180]. For the second and third stage, [-90, 90] and [-45, 45] respectively.

**Comment by brb-chen** [comment]
got it
