### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zaijianyingmu** [Jack-CV/PCN#31]
您好，请问Segmentation fault (core dumped)这个报错怎么解决呢是opencv版本问题还是其他什么问题，求指教

**Comment by zaijianyingmu** [comment]
> @zaijianyingmu this binary file may easily confuse people, source code will be released soon，just wait a few days.

thanks

**Comment by Jack-CV** [comment]
@zaijianyingmu I have released the source code
