### ISSUE TITLE
caffe+cpu+ubuntu14.04 can not use

### ISSUE THREAD

**Issue by jiagh2010** [Jack-CV/PCN#5]

**Comment by Jack-CV** [comment]
@jiagh2010  Thanks for your interest in our work. The binary file(libPCN.so) is compiled in ubuntu14.04, and the official caffe will be ok. I add some instructions in readme to run the demo.

**Comment by Edwardmark** [comment]
@Jack-CV I want to run your demo on GPU, what is your cuda and cudnn version?
